services:
  - type: web
    name: autometrics-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
